"""inventory core — product_variants, stock_adjustments, deleted_at

Revision ID: 1001883849f1
Revises: a1b2c3d4e5f6
Create Date: 2026-06-21 02:54:31.277196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1001883849f1'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('sku', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_messages_session'), table_name='agent_messages')
    op.drop_index(op.f('idx_calendar_tenant_range'), table_name='calendar_events')
    op.drop_index(op.f('idx_notifications_tenant_unread'), table_name='notifications', postgresql_where='(read_at IS NULL)')
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('idx_products_embedding'), table_name='products', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('idx_reports_tenant'), table_name='reports')
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks', postgresql_where="(status = ANY (ARRAY['pending'::task_status, 'approved'::task_status, 'in_progress'::task_status]))")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['tenant_id', 'status'], unique=False, postgresql_where="(status = ANY (ARRAY['pending'::task_status, 'approved'::task_status, 'in_progress'::task_status]))")
    op.create_index(op.f('idx_reports_tenant'), 'reports', ['tenant_id', 'generated_by', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_products_embedding'), 'products', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('products', 'cost',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('products', 'deleted_at')
    op.create_index(op.f('idx_notifications_tenant_unread'), 'notifications', ['tenant_id', 'created_at'], unique=False, postgresql_where='(read_at IS NULL)')
    op.create_index(op.f('idx_calendar_tenant_range'), 'calendar_events', ['tenant_id', 'starts_at', 'ends_at'], unique=False)
    op.create_index(op.f('idx_messages_session'), 'agent_messages', ['session_id', 'created_at'], unique=False)
    op.drop_table('stock_adjustments')
    op.drop_table('product_variants')
    # ### end Alembic commands ###
